List<Map<String, String>> dados = [
  {
    'id': '0',
    'foto':
        'https://media.istockphoto.com/id/1389348844/pt/foto/studio-shot-of-a-beautiful-young-woman-smiling-while-standing-against-a-grey-background.jpg?s=2048x2048&w=is&k=20&c=ZQVoPZnoApyV0vPa2C8469IdsWczQ5qR4NAOl43_b8Q=',
    'email': 'patriciaSilva@gmail.com',
    'nomeCompleto': 'Patricia Silva',
    'dataNascimento': '02/01/1995',
    'idade': '28',
    'altura': '1,85',
    'peso': '76',
    'genero': 'Feminino',
    'profissao': 'Professora 07:00 - 17:00',
    'estadoCivil': 'Solteira',
    'etnia': 'Caucasiana',
    'religiao': 'Cristã',
    'naturalidade': 'Brasileira',
    'endereco': 'Rua Amado Batista',
    'complemento': 'Hotel',
    'bairro': 'Bairro Roseira',
    'cidade': 'São João da Boa Vista',
    'estado': 'SP',
    'telefoneResidencial': '3633-9425',
    'telefoneCelular': '19 98990-2233',
    'escolaridade': 'Ensino Superior completo',
    'trabalhaAtualmente': 'Sim',
    'trabalhoAtivoParado': 'Parado',
    'habitos': 'Usar muito as Redes Sociais',
    'rendaFamiliar': '15 mil reais',
    'pressaoArterial': '',
    'frequenciaCardiaca': '',
    'glicemiaCapilar': '',
    'pulso': '',
    'temperatura': '',
    'saturacao': '',
    'frequenciaRespiratoria': '',
    'dores': '',
    'queixaPrincipal': '',
    'patologias': '',
    'antecedentes': '',
    'condicoesGerais': '',
    'marcapasso': '',
    'anticoncepcional': '',
    'cicloMenstrual': '',
    'gestante': '',
    'filhos': '',
    'alergias': '',
    'proteses': '',
    'sono': '',
    'funcionamentoIntestinal': '',
    'eliminacaoFisiologica': '',
    'locomocao': '',
    'tendenciaGanhoPeso': '',
    'efGeral': '',
    'efOlhos': '',
    'efPescoco': '',
    'estadoHigiene': '',
    'fumante': '',
    'frequenciaAlcoolica': '',
  },
  {
    'id': '1',
    'foto':
        'https://media.istockphoto.com/id/1396403999/pt/foto/look-to-the-future-with-hope.jpg?s=612x612&w=is&k=20&c=oIRcJ6M0moRzcSsDH1SfEYVZ0CtBlZwbY_lIdzx256c=',
    'email': 'veraalmeida@gmail.com',
    'nomeCompleto': 'Vera Almeida',
    'dataNascimento': '07/02/1990',
    'idade': '33',
    'altura': '1,75',
    'peso': '74',
    'genero': 'Feminino',
    'profissao': 'Professora 07:00 - 17:00',
    'estadoCivil': 'Solteira',
    'etnia': 'Caucasiana',
    'religiao': 'Cristã',
    'naturalidade': 'Brasileira',
    'endereco': 'Rua Amado Batista',
    'complemento': 'Hotel',
    'bairro': 'Bairro Roseira',
    'cidade': 'São João da Boa Vista',
    'estado': 'SP',
    'telefoneResidencial': '3633-9425',
    'telefoneCelular': '19 98990-2233',
    'escolaridade': 'Ensino Superior completo',
    'trabalhaAtualmente': 'Sim',
    'trabalhoAtivoParado': 'Parado',
    'habitos': 'Usar muito as Redes Sociais',
    'rendaFamiliar': '15 mil reais',
    'pressaoArterial': '12/8',
    'frequenciaCardiaca': '70',
    'glicemiaCapilar': '120',
    'pulso': '70',
    'temperatura': '27',
    'saturacao': '98%',
    'frequenciaRespiratoria': '18 mrm',
    'dores': 'Dores nas pernas',
    'queixaPrincipal': 'Dor na perna ao exercitar',
    'patologias': 'Nenhuma',
    'antecedentes': 'Nenhum',
    'condicoesGerais': 'Não',
    'marcapasso': 'Não',
    'anticoncepcional': 'Sim',
    'cicloMenstrual': 'Sim, Allestra 20',
    'gestante': 'Não',
    'filhos': '2',
    'alergias': 'Não tem',
    'proteses': 'Não tem',
    'sono': '8h',
    'funcionamentoIntestinal': 'Normal',
    'eliminacaoFisiologica': 'Normal',
    'locomocao': 'Normal',
    'tendenciaGanhoPeso': 'Não',
    'efGeral': 'Dores na perna',
    'efOlhos': 'Normal',
    'efPescoco': 'Normal',
    'estadoHigiene': 'Normal',
    'fumante': 'Não',
    'frequenciaAlcoolica': 'Fim de semanas',
  },
  {
    'id': '2',
    'foto':
        'https://cdn.pixabay.com/photo/2017/08/01/01/33/beanie-2562646_1280.jpg',
    'email': 'rafael.rocha@gmail.com',
    'nomeCompleto': 'Rafael Rocha',
    'dataNascimento': '05/05/2003',
    'idade': '20',
    'naturalidade': 'Brasileira',
    'genero': 'Masculino',
    'etnia': 'Caucasiana',
    'altura': '1,82',
    'peso': '70',
    'religiao': 'Ateu',
    'estadoCivil': 'Casado',
    'profissao': 'Gestão de TI - 06:00 - 20:00',
    'endereco': 'Rua José Sam',
    'complemento': 'Casa',
    'bairro': 'Bairro Roseira',
    'cidade': 'São João da Boa Vista',
    'estado': 'SP',
    'telefoneCelular': '19 94342-2233',
    'telefoneResidencial': '3623-9112',
  },
  {
    'id': '3',
    'foto':
        'https://cdn.pixabay.com/photo/2016/03/23/04/01/woman-1274056_1280.jpg',
    'email': 'mariamaria@gmail.com',
    'nomeCompleto': 'Maria almeida',
    'dataNascimento': '08/07/2000',
    'idade': '22',
    'naturalidade': 'Brasileira',
    'genero': 'Feminino',
    'etnia': '',
    'altura': '1,70',
    'peso': '60',
    'religiao': '',
    'estadoCivil': 'Solteira',
    'profissao': 'Estudante / 19:00 - 22:30',
    'endereco': 'Rua Lopes II',
    'complemento': 'Casa',
    'bairro': 'Bairro Flores',
    'cidade': 'São João da Boa Vista',
    'estado': 'SP',
    'telefoneCelular': '19 91421-4149',
    'telefoneResidencial': '3633-7632',
  }
];
